version: '3.4'

services:
  aggregator-grpc:
    image: mrartb/aggregatorgrpc
    build:
      context: .
      dockerfile: Aggregator.gRPC/Dockerfile
    
  agregator:
    image: mrartb/agregator
    build:
      context: .
      dockerfile: Agregator/Dockerfile

  catalog-api:
    image: mrartb/catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  identity:
    image: mrartb/identity
    build:
      context: .
      dockerfile: Identity/Dockerfile

  recordmanagment-api:
    image: mrartb/recordmanagmentapi
    build:
      context: .
      dockerfile: RecordManagment.API/Dockerfile

  writtenoffmanagement-api:
    image: mrartb/writtenoffmanagementapi
    build:
      context: .
      dockerfile: WrittenOff.API/Dockerfile

  gateway-api:
    image: mrartb/gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile

  library-db:
    image: mcr.microsoft.com/mssql/server:2019-latest

  redis-cache:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management
   
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  elasticsearch-data:
  sqlvolume: