apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: identity
  name: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: identity
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -f docker-compose.yml -f docker-compose.override.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: identity
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Server=library-db;Database=dotNet_Identity;User Id=sa;Password=dotNet_Pa$w0rd
            - name: Identity__IssuerUri
              value: http://identity:80
            - name: JWT__Audience
              value: IdentityApiUser
            - name: JWT__DurationInMinutes
              value: "1"
            - name: JWT__Issuer
              value: IdentityApi
            - name: JWT__Key
              value: 1807027DC4C4175B6618DE4F55CA4
          image: mrartb/identity
          name: identity
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
