apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -f docker-compose.yml -f docker-compose.override.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: recordmanagment-api
  name: recordmanagment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recordmanagment-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -f docker-compose.yml -f docker-compose.override.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: recordmanagment-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Server=library-db;Database=dotNet_RecordManagment;User Id=sa;Password=dotNet_Pa$w0rd
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
          image: mrartb/recordmanagmentapi
          name: recordmanagment-api
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
